function [summary] = mapdoppler(station,observations)

% valid_rockIDs is generated by the strewnhist function

P_min = 0.005 % min probability to consider

idx = categorical(observations.StationID) == station & observations.P_detect > P_min;
scatter3(observations.ObservationTime(idx), observations.observed_ELEV(idx), observations.P_detect(idx), observations.Diameter_m(idx).*1000, observations.Mass_kg(idx).*1000, 'filled');  

xlabel('Time');  
ylabel('Elevation Angle (degrees)');  
zlabel('Detection Probability');  
title('3D Scatter Plot of Detection Probability (Colored by Mass)');  

colorbar;  % Show color scale  
colormap(jet);  % Use 'jet' colormap for better contrast  
grid on;  
view(45, 30);  % Adjust viewing angle if needed  

summary = groupsummary(observations(idx,:), 'observed_ELEV', 'mean', 'P_detect');
