function [summary] = mapdoppler(station,observations,valid_observations)

% valid_rockIDs is generated by the strewnhist function

P_min = 0.005 % min probability to consider

% copy the valid data to a new table for processing in this function
valid_data = observations(valid_observations, :)

idx = categorical(valid_data.StationID) == station & valid_data.P_detect > P_min;
scatter3(valid_data.ObservationTime(idx), valid_data.observed_ELEV(idx), valid_data.P_detect(idx), valid_data.Diameter_m(idx).*1000, valid_data.Mass_kg(idx).*1000, 'filled');  

xlabel('Time');  
ylabel('Elevation Angle (degrees)');  
zlabel('Detection Probability');  
title('3D Scatter Plot of Detection Probability (Colored by Mass)');  

colorbar;  % Show color scale  
colormap(jet);  % Use 'jet' colormap for better contrast  
grid on;  
view(45, 30);  % Adjust viewing angle if needed  

summary = groupsummary(valid_data(idx,:), 'observed_ELEV', 'mean', 'P_detect');
